config_from_cf:
  cf_deployment_name: (( merge ))
  cf_director_uuid: (( merge ))
  cf_releases: (( merge ))
  cc:
    internal_api_password: (( merge ))
    srv_api_uri: (( merge ))
    staging_upload_user: (( merge ))
    staging_upload_password: (( merge ))
  consul:
    datacenter: (( merge ))
    log_level: (( merge ))
    lan_servers: (( merge ))
    ca_cert: (( merge ))
    agent_cert: (( merge ))
    agent_key: (( merge ))
    encrypt_keys: (( merge ))
    require_ssl: (( merge ))
    server_cert: (( merge ))
    server_key: (( merge ))
  loggregator:
    etcd_machines: (( merge ))
    shared_secret: (( merge ))
    traffic_controller_url: (( merge ))
  metron_agent:
    dropsonde_incoming_port: (( merge ))
  metron_endpoint:
    shared_secret: (( merge ))
  nats:
    user: (( merge ))
    password: (( merge ))
    port: (( merge ))
    machines: (( merge ))
  uaa:
    ssh_proxy_client_secret: (( merge ))
    token_url: (( merge ))
