config_from_cf:
  cf_deployment_name: (( merge ))
  cf_director_uuid: (( merge ))
  cf_release: (( merge ))
  cc:
    internal_api_user: (( merge ))
    internal_api_password: (( merge ))
    srv_api_uri: (( merge ))
  consul:
    datacenter: (( merge ))
    domain: (( merge ))
    log_level: (( merge ))
    lan_servers: (( merge ))
    ca_cert: (( merge ))
    agent_cert: (( merge ))
    agent_key: (( merge ))
    encrypt_keys: (( merge ))
    server_cert: (( merge ))
    server_key: (( merge ))
  etcd:
    advertise_urls_dns_suffix: (( merge ))
    ca_cert: (( merge ))
    client_cert: (( merge ))
    client_key: (( merge ))
    require_ssl: (( merge ))
  loggregator:
    etcd_ca_cert: (( merge ))
    etcd_require_ssl: (( merge ))
    etcd_machines: (( merge ))
    shared_secret: (( merge ))
    dropsonde_incoming_port: (( merge ))
    tls:
      ca_cert: (( merge ))
      metron:
        cert: (( merge ))
        key: (( merge ))

  metron_agent:
    dropsonde_incoming_port: (( merge ))
    grpc_port: (( merge ))
    protocols: (( merge ))
    preferred_protocol: (( merge ))
    tls:
      client_cert: (( merge ))
      client_key: (( merge ))
    etcd:
      client_cert: (( merge ))
      client_key: (( merge ))

  metron_endpoint:
    shared_secret: (( merge ))
  nats:
    user: (( merge ))
    password: (( merge ))
    port: (( merge ))
    machines: (( merge ))
  syslog_daemon_config: (( merge ))
  system_domain: (( merge ))
  uaa:
    tls_port: (( merge ))
    ca_cert: (( merge ))
    ssh_proxy_client_secret: (( merge ))
    tcp_emitter_client_secret: (( merge ))
  app_domains: (( merge ))
  sql:
    host: (( merge ))
    port: (( merge ))
    password: (( merge ))

