config_from_cf:
  cf_deployment_name: (( merge ))
  cc:
    external_port: (( merge ))
    internal_api_password: (( merge ))
    srv_api_uri: (( merge ))
    staging_upload_user: (( merge ))
    staging_upload_password: (( merge ))
  consul:
    log_level: (( merge ))
    lan_servers: (( merge ))
  etcd:
    machines: (( merge ))
  loggregator_endpoint:
    shared_secret: (( merge ))
  nats:
    user: (( merge ))
    password: (( merge ))
    port: (( merge ))
    machines: (( merge ))
  system_domain: (( merge ))
