config_from_cf:
  cf_director_uuid: (( merge ))
  cf_deployment_name: (( merge ))
  cc:
    internal_api_password: (( merge ))
    srv_api_uri: (( merge ))
    staging_upload_user: (( merge ))
    staging_upload_password: (( merge ))
  consul:
    log_level: (( merge ))
    lan_servers: (( merge ))
    ca_cert: (( merge ))
    agent_cert: (( merge ))
    agent_key: (( merge ))
    encrypt_keys: (( merge ))
    require_ssl: (( merge ))
    server_cert: (( merge ))
    server_key: (( merge ))
  etcd:
    machines: (( merge ))
  loggregator:
    etcd:
      machines: (( merge ))
  loggregator_endpoint:
    shared_secret: (( merge ))
  nats:
    user: (( merge ))
    password: (( merge ))
    port: (( merge ))
    machines: (( merge ))
  system_domain: (( merge ))
  uaa:
    clients:
      ssh-proxy:
        secret: (( merge ))
    url: (( merge || nil ))
  cf_releases: (( merge ))
