jq/jq-1.6-linux64.tgz:
  size: 1710406
  object_id: 903cbcb6-fc74-4434-4efc-e8ab36ea03bd
  sha: df0513a1ed80d8522d4a04dd03817e11de03d56e
proxy/envoy-3504d40f752eb5c20bc2883053547717bcb92fd8.tgz:
  size: 11796651
  object_id: 1078d488-bbfd-4f70-46c5-c303378049ed
  sha: fd0312a67c54528913c567ac4975bce501df9742
tar/tar-1503683828.tgz:
  size: 457686
  object_id: 2bf800f2-09ae-4b3a-4d9d-896dcee551ac
  sha: f00816474bcb03e76ef775b4214088651e323e5a
winpty/winpty-0.4.3.tgz:
  size: 461815
  object_id: a81bcf72-3eac-4899-74c5-f6176b4a9d5b
  sha: d2fe8662fd75829ecff4bd9832c0f31fc3ba90e1
