jq/jq-1.6-linux64.tgz:
  size: 1710406
  object_id: 903cbcb6-fc74-4434-4efc-e8ab36ea03bd
  sha: df0513a1ed80d8522d4a04dd03817e11de03d56e
proxy/envoy-4b5f5474f35763423684c0fe25c99cc7b2a01fcf-1.25.5.tgz:
  size: 89097421
  object_id: 236dc441-1902-417a-6500-03cafb960587
  sha: c2b2510a5e64e8beac2b98c9e3063cc5ae85f906
tar/tar-1503683828.tgz:
  size: 457686
  object_id: 2bf800f2-09ae-4b3a-4d9d-896dcee551ac
  sha: f00816474bcb03e76ef775b4214088651e323e5a
winpty/winpty-0.4.3.tgz:
  size: 461815
  object_id: a81bcf72-3eac-4899-74c5-f6176b4a9d5b
  sha: d2fe8662fd75829ecff4bd9832c0f31fc3ba90e1
