---
rootfs/lucid64.tar.gz:
  object_id: ee04984d-75d2-4496-814a-49aa2324b549
  sha: c37267bd6f79b2e5a1fd15a18417600c76b4b863
  size: 199595677
iptables/iptables-1.4.21.tar.bz2:
  object_id: 1c0b0768-4ea9-4d70-a9f2-06fd3c77c092
  sha: 85d4160537546a23a7e42bc26dd7ee62a0ede4c8
  size: 547439
shadow/shadow-4.2.1.tar.gz:
  object_id: 8f17023f-2a94-4d98-a737-ddbf166e7188
  sha: 1d205418863dd02b2b8af0fa78fcce5d7c848d1f
  size: 3686676
consul_0.4/consul:
  object_id: bb8108ec-b026-4ce4-8216-0fabfeaac904
  sha: 8be7984e9e1b7aab3d1eee14acdf59bb62207b6c
  size: 16085929
golang/go1.4.linux-amd64.tar.gz:
  object_id: bc1b6a23-ea89-4c16-b6ba-6bf8d3c33851
  sha: cd82abcb0734f82f7cf2d576c9528cebdafac4c6
  size: 63289725
cf-cli/cf-linux-amd64.tgz:
  object_id: 8bd6668a-5718-4661-815f-ae81c520e140
  sha: f845800310e4b702a39a2f1191e3d71862630103
  size: 4803309
consul/consul_0.5.0_linux_amd64.zip:
  object_id: 18a29a43-9576-4dff-857c-4c40e945b1af
  sha: 00e4c6e9ff2fb326d3b586fd86c3037f3b7e0974
  size: 4669655
rootfs/cflinuxfs2.tar.gz:
  object_id: 44a92529-e2da-442c-b653-02c9013f7a3e
  sha: b69e663ae9df6675eada50008e8eb5b3d0fd30c5
  size: 218215420
