golang/go1.9.6.linux-amd64.tar.gz:
  size: 118279574
  object_id: 0cd93afd-1f2a-48d4-6f1c-3d17e33c2e8e
  sha: 012c86a6b555272fe36fb9cdb45082ffc5ea5c7c
golang/go1.9.6.windows-amd64.zip:
  size: 123865846
  object_id: 2f29a14d-9d29-4660-43e3-e28d4cb9bf45
  sha: 5607cbbf34c73bb7fee690559852d46e75e0e1e3
jq/jq-1.5-linux64:
  size: 3027945
  object_id: b78765c7-2ce1-4a12-7a1d-6378a93af246
  sha: d8e36831c3c94bb58be34dd544f44a6c6cb88568
proxy/envoy-872728d4ad50acececaeae389da59cb72846cf89.tgz:
  size: 4611870
  object_id: 80d18d06-45c1-4f07-62e7-119dc21e5134
  sha: f691efcd25c7761383b114e332099be8a08f5c71
tar/tar-1503683828.tgz:
  size: 452214
  object_id: 2f1b2152-b17a-40d5-70f5-a4069c80ae8f
  sha: 4166d046bc684541fda6e75c6f2a2ac0edfd3bb2
winpty/winpty-0.4.3.tgz:
  size: 460765
  object_id: 53072e58-c940-41f2-7844-95f46adf90ab
  sha: 6bfe1962c47f10c1081410982d06b6eefaeb231c
