jq/jq-1.7.1-linux-amd64.tgz:
  size: 991585
  sha: sha256:31f0791bdbcb944c64da5b629b166530ce73cc6ad1b277245ec27152e03dd850
proxy/envoy-0de8b2b94c75dbe8c2f897058e16d23d959783fa-1.28.1.tgz:
  size: 24002360
  object_id: 217bbd54-3b07-47ba-69a2-831560c50062
  sha: sha256:97d0b397fd55e96ec221d6fbd715b549a1cadf374047a3c64679b4511291a14c
tar/tar-1503683828.tgz:
  size: 457686
  object_id: 2bf800f2-09ae-4b3a-4d9d-896dcee551ac
  sha: f00816474bcb03e76ef775b4214088651e323e5a
winpty/winpty-0.4.3.tgz:
  size: 461815
  object_id: a81bcf72-3eac-4899-74c5-f6176b4a9d5b
  sha: d2fe8662fd75829ecff4bd9832c0f31fc3ba90e1
