---
cf-cli/cf-linux-amd64.tgz:
  object_id: 446e6699-1108-476b-b42c-ab8147be5119
  sha: 28ae09d55ae3a156117a0e745c90e8b96d147ae2
  size: 5472279
golang/go1.4.3.linux-amd64.tar.gz:
  object_id: 57e504a8-c30c-4235-9eb5-42d046f84484
  sha: 332b64236d30a8805fc8dd8b3a269915b4c507fe
  size: 61210288
docker/docker-1.8.3:
  object_id: 91d23f11-4a32-45b5-b185-b52cb2ca58e0
  sha: 401971958a095fe2f9c42a35effb1b0245e52e87
  size: 21573264
rootfs/cflinuxfs2-1.37.0.tar.gz:
  object_id: e89f1b41-9bc4-4004-af7d-70e57040486c
  sha: 22f2fe0deeacd770f13b9e3c098569728ff87aee
  size: 258489635
lifecycles/windows_app_lifecycle-d627fe9.tgz:
  object_id: d67a3084-85e9-42b9-9297-2cb70c418bb2
  sha: ad70d4c1b9d36de0709a10fc3a2fe7632b13d9b9
  size: 4278799
